# key, Commons file, Wikidata search title, year, kind, blurb (written for dein.art)
FILMS = [
 ('trip-to-the-moon', 'Le Voyage dans la Lune (1902).webm', 'A Trip to the Moon', 1902, 'Fiction',
  'A club of astronomers fire themselves at the Moon in a cannon shell, meet its inhabitants and fall home into the sea. Painted sets, stage tricks and the most famous face in early cinema.'),
 ('man-with-a-movie-camera', 'Man With A Movie Camera (Dziga Vertov, 1929).webm', 'Man with a Movie Camera', 1929, 'Documentary',
  'One day in a Soviet city, from waking to night, with no story, no actors and no intertitles. The film shows its own cameraman at work and its own editor cutting it.'),
 ('nosferatu', 'Nosferatu (1922).webm', 'Nosferatu', 1922, 'Fiction',
  'A young clerk travels to the Carpathians to close a house sale with Count Orlok, and brings a plague home with him. Shot on real locations, in daylight, and still frightening.'),
 ('nanook-of-the-north', 'Nanook of the North (1922) by Robert J. Flaherty HD.webm', 'Nanook of the North', 1922, 'Documentary',
  'A year in the life of an Inuk hunter and his family in northern Quebec: building an igloo, hunting walrus, trading furs. Often called the first feature-length documentary.'),
 ('battleship-potemkin', 'Battleship Potemkin (1925) by Sergei Eisenstein.webm', 'Battleship Potemkin', 1925, 'Fiction',
  'The crew of a Russian battleship mutiny over rotten meat in 1905, and the city of Odessa pays for supporting them. The Odessa Steps sequence rewrote how films are cut.'),
 ('cabinet-of-dr-caligari', 'The Cabinet of Dr. Caligari (1920).webm', 'The Cabinet of Dr. Caligari', 1920, 'Fiction',
  'A fairground hypnotist exhibits a sleepwalker who predicts deaths, and the deaths begin. Painted shadows, crooked streets and a twist that changes everything before it.'),
 ('sherlock-jr', 'Sherlock Jr. (1924).webm', 'Sherlock Jr.', 1924, 'Fiction',
  'A cinema projectionist who wants to be a detective falls asleep at work and walks into the film he is showing. Forty-five minutes of stunts and camera tricks done for real.'),
 ('great-train-robbery', 'The Great Train Robbery (1903).webm', 'The Great Train Robbery', 1903, 'Short film',
  'Bandits hold up a train, rob the passengers and are chased down by a posse. Twelve minutes that showed how a film could cut between places to tell one story.'),
 ('the-general', 'The General (1926).webm', 'The General', 1926, 'Fiction',
  'A train engineer chases his stolen locomotive behind enemy lines during the American Civil War. The chase was filmed on real trains, including one dropped through a burning bridge.'),
 ('impossible-voyage', "Le Voyage à travers l'impossible (Georges Méliès, 1904).webm", 'The Impossible Voyage', 1904, 'Fiction',
  'A geographic society sets out for the Sun by train, automobile and submarine. Hand-coloured frame by frame.'),
 ('kino-eye', 'Kino Eye (1924) by Dziga Vertov.webm', 'Kino-Eye', 1924, 'Documentary',
  'Village life, a young pioneers camp and a market, filmed without staging. Meat turns back into a bull and bread back into wheat as the film runs backwards.'),
 ('within-our-gates', 'Within Our Gates HQ.webm', 'Within Our Gates', 1920, 'Fiction',
  'A schoolteacher travels north to raise money for a school for Black children in the South. The oldest surviving feature directed by an African American filmmaker.'),
 ('suspense', 'Suspense (Lois Weber and Phillips Smalley, 1913).webm', 'Suspense', 1913, 'Short film',
  'A mother alone with her baby, a tramp at the door and a husband racing home. Ten minutes, with a three-way split screen in 1913.'),
 ('gertie-the-dinosaur', 'Winsor McCay (1914)Gertie the Dinosaur.webm', 'Gertie the Dinosaur', 1914, 'Animation',
  'A cartoonist bets his friends he can bring a dinosaur to life, and draws ten thousand frames by hand to do it.'),
 ('arrival-of-a-train', "L'Arrivée d'un train en gare de La Ciotat (1897) par les frères Lumière.webm", "L'Arrivée d'un train en gare de La Ciotat", 1896, 'Documentary',
  'A train pulls into a station in the south of France. Fifty seconds, one shot, and one of the first films ever shown to a paying audience.'),
 ('fantasmagorie', 'Fantasmagorie (1908).webm', 'Fantasmagorie', 1908, 'Animation',
  'A stick figure moves through a world that keeps changing shape around him. Seven hundred drawings, and one of the first animated cartoons.'),
 ('one-week', 'One Week (1920).webm', 'One Week', 1920, 'Short film',
  'Newlyweds build a flat-pack house in seven days after a rival swaps the numbers on the crates.'),
 ('phantom-of-the-opera', 'The Phantom of the Opera (1925).webm', 'The Phantom of the Opera', 1925, 'Fiction',
  'A masked figure living beneath the Paris Opera makes a young singer a star, and demands she love him for it.'),
 ('safety-last', 'Safety Last (1923).webm', 'Safety Last!', 1923, 'Fiction',
  'A shop clerk promises his girl he has made it in the city, and ends up climbing the outside of a twelve-storey building.'),
 ('kingdom-of-the-fairies', 'Le Royaume des fées (Georges Méliès, 1903).webm', 'The Kingdom of the Fairies', 1903, 'Fiction',
  'A prince crosses the sea floor to rescue a princess carried off by a witch. One of the most elaborate films of its year.'),
 ('merry-frolics-of-satan', "Les Quat'Cents Farces du diable (Georges Méliès, 1906).webm", 'The Merry Frolics of Satan', 1906, 'Fiction',
  'An engineer sells his soul for a handful of magic pills and is driven across the sky in a coach pulled by a skeleton horse.'),
 ('conquest-of-the-pole', 'The Conquest of the Pole (1912) .webm', 'The Conquest of the Pole', 1912, 'Fiction',
  'An international expedition flies to the North Pole and meets the giant who lives in the ice.'),
 ('man-with-the-rubber-head', "L'Homme à la tête en caoutchouc (1901) par Georges Méliès.webm", 'The Man with the Rubber Head', 1901, 'Short film',
  'A chemist inflates a copy of his own head with a bellows until it bursts.'),
 ('melomaniac', 'Le Mélomane (1903).webm', 'The Melomaniac', 1903, 'Short film',
  'A music teacher throws his own head onto telegraph wires, again and again, to write out a tune.'),
 ('infernal-cauldron', 'Le Chaudron infernal (Georges Méliès, 1903).webm', 'The Infernal Cauldron', 1903, 'Short film',
  'A demon throws three people into a cauldron and their ghosts come back for him. Under two minutes, hand-coloured.'),
 ('bluebeard', 'Barbe bleue (1901).webm', 'Bluebeard', 1901, 'Fiction',
  'A bride is given every key in the castle and told not to use one of them.'),
 ('eclipse', "L'éclipse du soleil en pleine lune (1907).webm", 'The Eclipse: Courtship of the Sun and Moon', 1907, 'Fiction',
  'An astronomy professor and his students watch the Sun and the Moon meet.'),
]
